const pizzas = [
  {
    id: 1,
    name: "Margherita",
    ingredients: ["Tomato", "Mozzarella", "Basil"],
    stock: 10,
    quantity: 0,
    price: 5000,
    image: "../img/Header.jpg",
  },
  {
    id: 2,
    name: "Pepperoni",
    ingredients: ["Tomato", "Mozzarella", "Pepperoni"],
    stock: 8,
    quantity: 0,
    price: 8500,
    image: "../img/Header2.jpg",
  },
  {
    id: 3,
    name: "Funghi",
    ingredients: ["Tomato", "Mozzarella", "Mushrooms"],
    stock: 6,
    quantity: 0,
    price: 4750,
    image: "../img/Header3.jpg",
  },
  {
    id: 4,
    name: "Hawaiian",
    ingredients: ["Tomato", "Mozzarella", "Pineapple", "Ham"],
    stock: 7,
    quantity: 0,
    price: 9580,
    image: "../img/Header4.jpg",
  },
  {
    id: 5,
    name: "Quattro Formaggi",
    ingredients: ["Tomato", "Mozzarella", "Parmesan", "Gorgonzola", "Ricotta"],
    stock: 9,
    quantity: 0,
    price: 10520,
    image: "../img/Header5.jpg",
  },
  {
    id: 6,
    name: "Diavola",
    ingredients: ["Tomato", "Mozzarella", "Spicy Salami", "Red Pepper Flakes"],
    stock: 5,
    quantity: 0,
    price: 6690,
    image: "../img/Header6.jpg",
  },
  {
    id: 7,
    name: "BBQ Chicken",
    ingredients: ["BBQ Sauce", "Mozzarella", "Chicken", "Red Onions"],
    stock: 6,
    quantity: 0,
    price: 7780,
    image: "../img/Header7.jpg",
  },
  {
    id: 8,
    name: "Vegetarian",
    ingredients: ["Tomato", "Mozzarella", "Bell Peppers", "Onions", "Olives"],
    stock: 10,
    quantity: 0,
    price: 9850,
    image: "../img/Header8.jpg",
  },
  {
    id: 9,
    name: "Capricciosa",
    ingredients: ["Tomato","Mozzarella","Ham","Artichokes","Mushrooms","Olives"],
    stock: 8,
    quantity: 0,
    price: 12580,
    image: "../img/Header9.jpg",
  },
];

export default pizzas;
